import { Charity } from "./supabase/types";

export const DEFAULT_CHARITIES: Charity[] = [
  {
    id: "c1111111-1111-1111-1111-111111111111",
    name: "Golf for Youth Foundation",
    slug: "golf-for-youth-foundation",
    short_description: "Providing inner-city youth with access to golf equipment, coaching, and life skills.",
    long_description: "Golf for Youth Foundation breaks financial barriers for young aspiring golfers. We fund junior golf memberships, equipment, and tournament entries across underserved communities.",
    logo_url: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=1200&q=80",
    category: "Youth & Sports",
    website_url: "https://example.org/golf-youth",
    registration_number: "UK-CH-882910",
    is_featured: true,
    is_active: true,
    total_raised_pence: 450000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c2222222-2222-2222-2222-222222222222",
    name: "Green Greens Environmental Trust",
    slug: "green-greens-environmental-trust",
    short_description: "Restoring natural habitats, biodiversity, and sustainable water management on golf courses.",
    long_description: "Partnering with UK golf clubs to plant native trees, construct wetland sanctuaries, and eliminate single-use plastics from course maintenance operations.",
    logo_url: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80",
    category: "Environment",
    website_url: "https://example.org/green-greens",
    registration_number: "UK-CH-551920",
    is_featured: true,
    is_active: true,
    total_raised_pence: 320000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c3333333-3333-3333-3333-333333333333",
    name: "Veteran Golfers Alliance",
    slug: "veteran-golfers-alliance",
    short_description: "Supporting military veterans through therapeutic golf programs, camaraderie, and rehab.",
    long_description: "Empowering wounded and recovering service members through adaptive golf equipment, weekly peer rounds, and mental health counseling.",
    logo_url: "https://images.unsplash.com/photo-1592919505780-303950717480?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1592919505780-303950717480?auto=format&fit=crop&w=1200&q=80",
    category: "Veterans & Health",
    website_url: "https://example.org/veteran-golf",
    registration_number: "UK-CH-119284",
    is_featured: false,
    is_active: true,
    total_raised_pence: 680000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "c4444444-4444-4444-4444-444444444444",
    name: "Cancer Research Golf Society",
    slug: "cancer-research-golf-society",
    short_description: "Funding life-saving clinical trials and medical research through charity golf days.",
    long_description: "Organizing charity golf tournaments and donor subscriptions to advance targeted cancer therapies and early diagnostic testing.",
    logo_url: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=300&q=80",
    banner_url: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
    category: "Medical Research",
    website_url: "https://example.org/cancer-golf",
    registration_number: "UK-CH-994012",
    is_featured: false,
    is_active: true,
    total_raised_pence: 1250000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEFAULT_DRAWS: any[] = [
  {
    id: "demo",
    period_month: "2026-10-01",
    winning_numbers: [7, 14, 21, 28, 35],
    total_pool_pence: 125000,
    rollover_in_pence: 25000,
    rollover_out_pence: 50000,
    status: "published",
    mode: "algorithmic",
    seed: "demo-seed-1",
    published_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    winners: [
      {
        id: "w1",
        draw_id: "demo",
        user_id: "u1",
        tier: 5,
        match_count: 5,
        prize_amount_pence: 50000,
        payout_status: "paid",
        verification_status: "approved",
      },
      {
        id: "w2",
        draw_id: "demo",
        user_id: "u2",
        tier: 4,
        match_count: 4,
        prize_amount_pence: 21875,
        payout_status: "approved",
        verification_status: "approved",
      },
      {
        id: "w3",
        draw_id: "demo",
        user_id: "u3",
        tier: 3,
        match_count: 3,
        prize_amount_pence: 15625,
        payout_status: "pending",
        verification_status: "pending",
      },
    ],
  },
];
